<a href="https://colab.research.google.com/github/farcryson/Titanic_problem_CatBoost/blob/main/Updated_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Titanic Problem**
**Dataset Link: https://www.kaggle.com/competitions/titanic**


# **Importing** **Libraries**

In [ ]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 2.4 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np

# **Importing** **Dataset**

In [ ]:
dataset = pd.read_csv('train.csv')

In [ ]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# **Data Cleaning**

In [ ]:
X = dataset.drop(['Survived','PassengerId','Name','Ticket','Cabin'], axis=1).values

In [ ]:
print(X)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' nan ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


In [ ]:
print(X)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' nan ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


In [ ]:
y = dataset['Survived'].values

In [ ]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

# **Filling null values**

In [ ]:
from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values =np.nan, strategy ='mean')
imputer2 = SimpleImputer(missing_values =np.nan, strategy ='most_frequent')
imputer1.fit(X[:, 2:3])
X[:, 2:3] = imputer1.transform(X[:, 2:3])

In [ ]:
print(X)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' 29.69911764705882 ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


In [ ]:
imputer2.fit(X[:, 6:7])
X[:, 6:7] = imputer2.transform(X[:, 6:7])

In [ ]:
print(X)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' 29.69911764705882 ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


# **One Hot Encoding categorical columns**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[1,6])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 0.0 ... 1 0 7.25]
 [1.0 0.0 1.0 ... 1 0 71.2833]
 [1.0 0.0 0.0 ... 0 0 7.925]
 ...
 [1.0 0.0 0.0 ... 1 2 23.45]
 [0.0 1.0 1.0 ... 0 0 30.0]
 [0.0 1.0 0.0 ... 0 0 7.75]]


# **Splitting dataset into training and validation sets**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# **Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Training the model**

XBGClassifier

In [ ]:
# import xgboost
# classifier = xgboost.XGBClassifier()
# classifier.fit(X_train, y_train)

Logistic Regression

In [ ]:
# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression(random_state = 0)
# classifier.fit(X_train, y_train)

Decision Tree Classification

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)

K-nearest Neighbours


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

Kernel SVM

In [ ]:
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0)
# classifier.fit(X_train, y_train)

Naive Bayes

In [ ]:
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# classifier.fit(X_train, y_train)

Random Forest Classification

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)

Support Vector Machine (SVM)

In [ ]:
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'linear', random_state = 0)
# classifier.fit(X_train, y_train)

Catboost

In [ ]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

Learning rate set to 0.008911
0:	learn: 0.6863198	total: 48.1ms	remaining: 48.1s
1:	learn: 0.6805287	total: 49.4ms	remaining: 24.6s
2:	learn: 0.6751397	total: 50.2ms	remaining: 16.7s
3:	learn: 0.6693560	total: 51.4ms	remaining: 12.8s
4:	learn: 0.6631831	total: 52.5ms	remaining: 10.4s
5:	learn: 0.6570137	total: 53.9ms	remaining: 8.92s
6:	learn: 0.6508794	total: 55.1ms	remaining: 7.81s
7:	learn: 0.6451386	total: 56.3ms	remaining: 6.98s
8:	learn: 0.6406015	total: 57.5ms	remaining: 6.33s
9:	learn: 0.6359644	total: 58.8ms	remaining: 5.82s
10:	learn: 0.6306842	total: 59.9ms	remaining: 5.39s
11:	learn: 0.6253821	total: 61.2ms	remaining: 5.04s
12:	learn: 0.6197169	total: 62.5ms	remaining: 4.74s
13:	learn: 0.6145245	total: 63.9ms	remaining: 4.5s
14:	learn: 0.6103798	total: 65.1ms	remaining: 4.28s
15:	learn: 0.6055589	total: 66.4ms	remaining: 4.08s
16:	learn: 0.6008282	total: 67.6ms	remaining: 3.91s
17:	learn: 0.5976011	total: 68.6ms	remaining: 3.74s
18:	learn: 0.5928956	total: 69.8ms	remaining:

# **Predicting Validation set**

In [ ]:
y_pred = classifier.predict(X_test)

# **Checking accuracy and applying K-fold cross validation**

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[98  8]
 [33 40]]


0.770949720670391

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Streaming output truncated to the last 5000 lines.
6:	learn: 0.6535990	total: 8.4ms	remaining: 1.19s
7:	learn: 0.6481791	total: 9.77ms	remaining: 1.21s
8:	learn: 0.6430997	total: 10.9ms	remaining: 1.2s
9:	learn: 0.6381740	total: 12.3ms	remaining: 1.22s
10:	learn: 0.6331206	total: 13.7ms	remaining: 1.23s
11:	learn: 0.6281717	total: 15.1ms	remaining: 1.24s
12:	learn: 0.6229233	total: 16.4ms	remaining: 1.25s
13:	learn: 0.6181955	total: 17.8ms	remaining: 1.25s
14:	learn: 0.6143845	total: 19.2ms	remaining: 1.26s
15:	learn: 0.6102372	total: 20.3ms	remaining: 1.25s
16:	learn: 0.6056552	total: 21.5ms	remaining: 1.24s
17:	learn: 0.6026237	total: 22.3ms	remaining: 1.22s
18:	learn: 0.5977051	total: 23.7ms	remaining: 1.23s
19:	learn: 0.5930794	total: 25.2ms	remaining: 1.23s
20:	learn: 0.5892620	total: 26.4ms	remaining: 1.23s
21:	learn: 0.5852798	total: 27.6ms	remaining: 1.23s
22:	learn: 0.5812337	total: 28.8ms	remaining: 1.22s
23:	learn: 0.5773841	total: 30.1ms	remaining: 1.22s
24:	learn: 0.573212

# **Importing Test dataset and repeating steps as train dataset**

In [ ]:
test = pd.read_csv('test.csv')

In [ ]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
test.isnull().any()

PassengerId    False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin           True
Embarked       False
dtype: bool

In [ ]:
test_X = test.drop(['PassengerId','Name','Ticket','Cabin'], axis=1).values

In [ ]:
print(test_X)

[[3 'male' 34.5 ... 0 7.8292 'Q']
 [3 'female' 47.0 ... 0 7.0 'S']
 [2 'male' 62.0 ... 0 9.6875 'Q']
 ...
 [3 'male' 38.5 ... 0 7.25 'S']
 [3 'male' nan ... 0 8.05 'S']
 [3 'male' nan ... 1 22.3583 'C']]


In [ ]:
test_imputer = SimpleImputer(missing_values =np.nan, strategy ='mean')
test_imputer.fit(test_X[:, 2:3])
test_X[:, 2:3] = test_imputer.transform(test_X[:, 2:3])

In [ ]:
test_imputer2 = SimpleImputer(missing_values =np.nan, strategy ='mean')
test_imputer2.fit(test_X[:, 5:6])
test_X[:, 5:6] = test_imputer2.transform(test_X[:, 5:6])

In [ ]:
ct_test = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[1,6])], remainder= 'passthrough')
test_X = np.array(ct_test.fit_transform(test_X))

In [ ]:
sc_test = StandardScaler()
test_X = sc_test.fit_transform(test_X)

In [ ]:
y_predict = classifier.predict(test_X)

In [ ]:
y_predict.shape

(418,)

# **Getting the submission file**

In [ ]:
temp = pd.read_csv('gender_submission.csv')

In [ ]:
pred = pd.DataFrame(y_predict)

In [ ]:
output = pd.concat([temp['PassengerId'],pred],axis=1)

In [ ]:
output.columns = ['PassengerId', 'Survived']

In [ ]:
output.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [ ]:
output.to_csv('output_catboost.csv', index= False)